#! /bin/bash
# set -ex

function build() {
    cross_info=$(
        cat <<EOF
1) x86_64-unknown-linux-musl
2) aarch64-unknown-linux-musl
3) x86_64-apple-darwin
4) aarch64-apple-darwin
5) x86_64-pc-windows-gnu
选择目标平台的编号:
EOF
    )
    name=mmfplace
    read -p "$cross_info" number
    case $number in
    1)
        platform=x86_64-unknown-linux-musl
        ;;
    2)
        platform=aarch64-unknown-linux-musl
        ;;
    3)
        platform=x86_64-apple-darwin
        ;;
    4)
        platform=aarch64-apple-darwin
        ;;
    5)
        platform=x86_64-pc-windows-gnu
        name=mmfplace.exe
        ;;
    *)
        platform=x86_64-unknown-linux-musl
        ;;
    esac

    dist=mmfplace.$platform
    output=./dist/$dist
    [ -d "$output" ] || mkdir -p $output
    # build testing
    cd builder && cargo build && cd ..
    cd builder && cross build --release --target $platform -vv && cd ..
    cp builder/target/$platform/release/$name $output/$name
    cd ./dist && tar -czvf $dist.tar.gz $dist && rm -rf $dist && cd ..
    echo "Build success, output file: $output.tar.gz"
}

build
