[package]
name = "config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
futures = "0.3.28"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.16"
