[build]
xargo = false
build-std = false
default-target = "x86_64-unknown-linux-musl"
# pre-build = ["apt-get update"] # can also be the path to a file to run

[target.x86_64-unknown-linux-musl]
image = "idhyt/cross-rs-x86_64-unknown-linux-musl:0.2.5"

[target.aarch64-unknown-linux-musl]
image = "idhyt/cross-rs-aarch64-unknown-linux-musl:0.0.1"

[target.x86_64-apple-darwin]
image = "idhyt/cross-rs-x86_64-apple-darwin:0.0.1"

[target.aarch64-apple-darwin]
image = "idhyt/cross-rs-aarch64-apple-darwin:0.0.1"

[target.x86_64-pc-windows-gnu]
image = "yosyshq/cross-windows-x64:2.2"
